PRIORITIES = {
    'blocker': 1,
    'blocker a': 1,
    'highest': 1,
    'very hight': 1,
    'critical': 1,
    'major': 2,
    'major b': 2,
    'high': 2,
    'normal': 3,
    'task': 3,
    'minor': 3,
    'minor c': 3,
    'defect': 3,
    'trivial': 3,
    'low': 3,
    'lowest': 3,
    'very low': 3,
    'enhancement high': 4,
    'enhancement medium': 5,
    'enhancement low': 5,
}
